meta_name: "Arstanbek Zholochu Portfolio"
meta_title: "My web apps and projects"
meta_description: "My portfolio page includes completed and ongoing projects."
meta_image: "Arstanbek Zholochu Portfolio.png"
